### ISSUE TITLE
Replace pycrypto with pycryptodome

### ISSUE THREAD

**Issue by erickearns** [LedgerHQ/blue-loader-python#44]
Using ledgerblue in coordination with various Ethereum tools (e.g. https://github.com/ethereum/web3.py/blob/master/setup.py#L27) is problematic as pycryptodome has replaced pycrypto in most modern tool dependency trees. As pycryptodome is largely a drop-in replacement for pycrypto, updating this dependency would solve a significant amount of headache.

**Comment by redshiftzero** [comment]
Heads up, we made this same change in SecureDrop, replacing pycrypto with pycryptodome (ref: https://github.com/freedomofpress/securedrop/pull/2903). However, since we did that we were strongly advised for security reasons to move away from pycryptodome to pyca/cryptography (refs: https://github.com/PyCQA/bandit/pull/307, https://github.com/freedomofpress/securedrop/issues/3399, https://github.com/freedomofpress/securedrop/pull/3458). If using audited crypto libraries is important for this project, you may want to do the same, though I understand that this may be significantly more work.
